// <auto-generated />
using InventoryApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("InventoryApi.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wireless Mouse",
                            Price = 4500m,
                            QuantityInStock = 120,
                            ReorderLevel = 20,
                            Sku = "WM-001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mechanical Keyboard",
                            Price = 18500m,
                            QuantityInStock = 45,
                            ReorderLevel = 10,
                            Sku = "MK-002"
                        },
                        new
                        {
                            Id = 3,
                            Name = "USB-C Hub",
                            Price = 9200m,
                            QuantityInStock = 8,
                            ReorderLevel = 15,
                            Sku = "UH-003"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
